name: CI

on:
    pull_request:
        branches:
            - '**'

jobs:
    build:
        name: Build Project
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout Code
                uses: actions/checkout@v4

            -   uses: actions/setup-node@v4
                with:
                    node-version: 20

            -   uses: pnpm/action-setup@v3
                with:
                    version: 'latest'
                    run_install: true

            -   name: Prettify package.json
                run: ./node_modules/.bin/prettier-package-json --use-tabs --list-different

            -   run: pnpm build
