name: "Deploy to Fly.io"

on:
    push:
        branches:
            - live

env:
    FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
    build:
        uses: 21torr/docs/.github/workflows/ci.yml@live

    deploy:
        name: Deploy to Fly.io
        runs-on: ubuntu-latest
        needs: build

        steps:
            -   uses: actions/checkout@v3

            -   uses: actions/download-artifact@v3
                with:
                    name: build-dir

            -   uses: superfly/flyctl-actions/setup-flyctl@master

            -   run: flyctl deploy --remote-only
